use_frameworks!

platform :ios, '9.0'

target 'iOSTestComponent_Example' do
  pod 'iOSTestComponent', :path => '../'

  target 'iOSTestComponent_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
